# Generated by Django 4.2.6 on 2023-10-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='likes',
        ),
    ]
