# Generated by Django 4.2.6 on 2023-10-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_remove_myuser_comments_remove_myuser_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturepost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='picturepost',
            name='likes',
        ),
    ]
