# Generated by Django 4.2.6 on 2023-10-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_remove_picturepost_comments_remove_picturepost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturepost',
            name='comments_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picturepost',
            name='likes_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
